version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/main.go
    binary: imds
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.commit={{.FullCommit}}
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

homebrew_casks:
  - name: imds
    repository:
      owner: bwagner5
      name: homebrew-wagner
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/bwagner5/imds"
    description: "CLI and TUI for EC2 Instance Metadata Service (IMDS)"
    binaries:
      - imds

nfpms:
  - maintainer: Brandon Wagner <bwagner5@users.noreply.github.com>
    description: CLI and TUI for EC2 Instance Metadata Service (IMDS)
    license: Apache-2.0
    formats:
      - deb
      - rpm
